#!/usr/bin/env perl 
use strict;
use warnings;
use utf8;
use feature qw(say);

# Take file generated by Create-File.pl as input
# Output an sorted file
my $o = 0;
for (3 .. 60) # In this case, we know we're sorting ages
{
	my $age = $_;
	print "$age now\n" if $age != $o;
	$o = $age;
	search_by_age($age);
}

sub search_by_age
{
	open( IN,  "$ARGV[0]"  );
	open( OUT, ">>Out.txt" );
	my $age = shift;
	my $out = "";
	while(<IN>)
	{
		my @line = split(/\s+/, $_);	
		if ( $age != $line[1] )
		{
			next;	
		}
		else
		{
			$out .= $_;
		}
	}
	print OUT $out;
	close(IN);
	close(OUT);
}
